const TRANSLATIONS = {
  fr: {
    newGame: 'Nouvelle Partie',
    loadGame: 'Charger une Partie',
    configuration: 'Configuration',
    players: 'Joueurs',
    addOpponent: '+ Ajouter un adversaire',
    mapSettings: 'Paramètres de la Carte',
    back: '← Retour',
    startGame: 'Lancer la Partie',
    computer: 'Ordinateur',
    you: 'Vous',
    colName: 'Nom',
    colCiv: 'Civilisation',
    colColor: 'Couleur',
    mapSizeLabel: 'Carte',
    aiDifficulty: 'Difficulté IA',
    startingResourcesLabel: 'Ressources de départ',
    devMode: 'Mode dev (instant build)',
    revealAll: 'Tout révéler',
    revealTerrain: 'Révéler le terrain',
    removePlayer: 'Retirer ce joueur',
    colorSwatch: 'Couleur : {color} (cliquer pour changer)',
    diffEasy: 'Facile  — IA lente, pop réduite',
    diffMedium: 'Moyen   — IA standard',
    diffHard: 'Difficile — IA rapide, pop accrue',
    resLow: 'Bas      — 100 / 150 / 50 / 0',
    resStandard: 'Standard — 200 / 200 / 150 / 0',
    resHigh: 'Élevé    — 500 / 500 / 300 / 0',
    resVeryHigh: 'Très élevé — 1000 / 1000 / 750 / 100',
    civGreek: 'Grecque',
    menuBtn: 'Menu',
    save: 'Sauvegarder',
    load: 'Charger',
    quit: 'Quitter',
    cancel: 'Annuler',
    pause: 'Pause',
    wood: 'bois',
    food: 'nourriture',
    stone: 'pierre',
    gold: 'or',
    needMore: 'Vous avez besoin de plus de {resource} !',
    loadingConfig: 'Chargement config..',
    loadingInterface: 'Chargement interface..',
    loadingSeeds: 'Chargement seeds..',
    loadingTerrain: 'Chargement terrain..',
    loadingBorder: 'Chargement bordures..',
    loadingGraphics: 'Chargement graphismes..',
    loadingSounds: 'Chargement sons..',
    stoneAge: 'Âge de Pierre',
    toolAge: 'Âge des Outils',
    bronzeAge: 'Âge de Bronze',
    ironAge: 'Âge de Fer',
    needHouses: 'Vous devez construire plus de maisons',
    // Types affichés dynamiquement dans bottombar-info
    Greek: 'Grecque',
    Tree: 'Arbre',
    Berrybush: 'Buisson de baies',
    Stone: 'Pierre',
    Gold: 'Or',
    Salmon: 'Saumon',
    House: 'Maison',
    Dock: 'Quai',
    TownCenter: 'Centre-ville',
    Farm: 'Ferme',
    StoragePit: 'Entrepôt',
    Granary: 'Grenier',
    Barracks: 'Caserne',
    Market: 'Marché',
    ArcheryRange: "Champ de tir",
    Stable: 'Écurie',
    Academy: 'Académie',
    WatchTower: 'Tour de guet',
    SentryTower: 'Tour sentinelle',
    Villager: 'Villageois',
    Priest: 'Prêtre',
    Clubman: 'Gourdinier',
    fisher: 'Pêcheur',
    hunter: 'Chasseur',
    farmer: 'Fermier',
    forager: 'Cueilleur',
    woodcutter: 'Bûcheron',
    stoneminer: 'Mineur (pierre)',
    goldminer: 'Mineur (or)',
    builder: 'Constructeur',
    attacker: 'Attaquant',
    healer: 'Guérisseur',
  },
  en: {
    newGame: 'New Game',
    loadGame: 'Load Game',
    configuration: 'Configuration',
    players: 'Players',
    addOpponent: '+ Add opponent',
    mapSettings: 'Map Settings',
    back: '← Back',
    startGame: 'Start Game',
    computer: 'Computer',
    you: 'You',
    colName: 'Name',
    colCiv: 'Civilization',
    colColor: 'Color',
    mapSizeLabel: 'Map',
    aiDifficulty: 'AI Difficulty',
    startingResourcesLabel: 'Starting Resources',
    devMode: 'Dev mode (instant build)',
    revealAll: 'Reveal everything',
    revealTerrain: 'Reveal terrain',
    removePlayer: 'Remove player',
    colorSwatch: 'Color: {color} (click to change)',
    diffEasy: 'Easy   — Slow AI, reduced pop',
    diffMedium: 'Medium — Standard AI',
    diffHard: 'Hard   — Fast AI, increased pop',
    resLow: 'Low      — 100 / 150 / 50 / 0',
    resStandard: 'Standard — 200 / 200 / 150 / 0',
    resHigh: 'High     — 500 / 500 / 300 / 0',
    resVeryHigh: 'Very High — 1000 / 1000 / 750 / 100',
    civGreek: 'Greek',
    menuBtn: 'Menu',
    save: 'Save',
    load: 'Load',
    quit: 'Quit',
    cancel: 'Cancel',
    pause: 'Pause',
    wood: 'wood',
    food: 'food',
    stone: 'stone',
    gold: 'gold',
    needMore: 'You need more {resource}!',
    loadingConfig: 'Loading config..',
    loadingInterface: 'Loading interface..',
    loadingSeeds: 'Loading seeds..',
    loadingTerrain: 'Loading terrain..',
    loadingBorder: 'Loading border..',
    loadingGraphics: 'Loading graphics..',
    loadingSounds: 'Loading sounds..',
    stoneAge: 'Stone Age',
    toolAge: 'Tool Age',
    bronzeAge: 'Bronze Age',
    ironAge: 'Iron Age',
    needHouses: 'You need to build more houses',
    // Types displayed dynamically in bottombar-info
    Greek: 'Greek',
    Tree: 'Tree',
    Berrybush: 'Berrybush',
    Stone: 'Stone',
    Gold: 'Gold',
    Salmon: 'Salmon',
    House: 'House',
    Dock: 'Dock',
    TownCenter: 'Town Center',
    Farm: 'Farm',
    StoragePit: 'Storage Pit',
    Granary: 'Granary',
    Barracks: 'Barracks',
    Market: 'Market',
    ArcheryRange: 'Archery Range',
    Stable: 'Stable',
    Academy: 'Academy',
    WatchTower: 'Watch Tower',
    SentryTower: 'Sentry Tower',
    Villager: 'Villager',
    Priest: 'Priest',
    Clubman: 'Clubman',
    fisher: 'Fisher',
    hunter: 'Hunter',
    farmer: 'Farmer',
    forager: 'Forager',
    woodcutter: 'Woodcutter',
    stoneminer: 'Stone Miner',
    goldminer: 'Gold Miner',
    builder: 'Builder',
    attacker: 'Attacker',
    healer: 'Healer',
  },
}

let currentLang = localStorage.getItem('lang') || 'fr'

export function t(key, vars) {
  let str = TRANSLATIONS[currentLang][key] ?? TRANSLATIONS.en[key] ?? key
  if (vars) {
    Object.entries(vars).forEach(([k, v]) => {
      str = str.replace(`{${k}}`, v)
    })
  }
  return str
}

export function setLang(lang) {
  currentLang = lang
  localStorage.setItem('lang', lang)
}

export function getLang() {
  return currentLang
}
