packages:
  - .

allowBuilds:
  electron-winstaller: false

overrides:
  tar: '>=7.5.8'
  serialize-javascript: '>=7.0.3'
  uuid: '>=11.1.1'
  electron-builder-squirrel-windows: 26.14.0
  form-data: ^4.0.6
  undici: ^7.28.0
  node-gyp>undici: ^6.27.0
  http-proxy-middleware: ^2.0.10
  webpack-dev-server: ^5.2.5
