const names = {
  male: [
    'Amani',
    'Akinidad',
    'Aktisanes',
    'Arakamani',
    'Arikankharor',
    'Aspelta',
    'Atlanersa',
    'Harsiotef',
    'Karkamani',
    'Kash',
    'Malewiebamani',
    'Malonaqen',
    'Nasakhma',
    'Natakamani',
    'Piye',
    'Sabrakamani',
    'Senkamanisken',
    'Shabaka',
    'Shabataka',
    'Talakhamani',
    'Tanwetamani',
    'Tanyidamani',
    'Terkamani',
    'Yesebokheamani',
  ],
  female: [
    'Amanikhatashan',
    'Amanimalel',
    'Amanirenas',
    'Amanishakheto',
    'Amanitore',
    'Bartare',
    'Kandake',
    'Maletasen',
    'Nawidemak',
    'Shanakdakhete',
    'Tagtal',
    'Wetar',
  ],
}

export default names
