#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from config import PALETTES, PROJECT_ROOT


DEFAULT_OUTPUT = PROJECT_ROOT / "app/lib/lpc/generatedPalettes.ts"
RUNTIME_PALETTES = (
    "brown_hair",
    "black",
    "dark_brown",
    "light_brown",
    "blond",
    "white",
)


def rgb(hex_color: str) -> int:
    return int(hex_color.removeprefix("#"), 16)


def luminance(color: int) -> float:
    r = (color >> 16) & 0xFF
    g = (color >> 8) & 0xFF
    b = color & 0xFF
    return 0.299 * r + 0.587 * g + 0.114 * b


def runtime_palette(name: str) -> list[int]:
    # Runtime replacement maps source colors from light to dark. The Python LPC
    # palettes are authored mostly dark to light, so sort explicitly instead of
    # relying on authoring order.
    return sorted((rgb(color) for color in PALETTES[name]), key=luminance, reverse=True)


def ts_array(values: list[int]) -> str:
    return "[" + ", ".join(f"0x{value:06x}" for value in values) + "]"


def write_runtime_palettes(output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by scripts/lpc/export_runtime_palettes.py from scripts/lpc/config.py.",
        "// Do not edit by hand.",
        "",
        "export const LPC_RUNTIME_PALETTES = {",
    ]
    for name in RUNTIME_PALETTES:
        lines.append(f"  {name}: {ts_array(runtime_palette(name))},")
    lines.extend([
        "} as const",
        "",
        "export const LPC_RUNTIME_SOURCE_PALETTES = {",
        "  brown_hair: LPC_RUNTIME_PALETTES.brown_hair,",
        "} as const",
        "",
    ])
    output.write_text("\n".join(lines), encoding="utf8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Export LPC palettes used by the TypeScript runtime.")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    write_runtime_palettes(args.out)


if __name__ == "__main__":
    main()
