type AssetBundle = Record<string, string>

function toTextureBundle(basePath: string, ids: string[]): AssetBundle {
  return ids.reduce((bundle: AssetBundle, id) => {
    bundle[id] = `${basePath}/${id}/texture.json`
    return bundle
  }, {})
}

function toSoundBundle(ids: string[]): AssetBundle {
  return ids.reduce((bundle: AssetBundle, id) => {
    bundle[id] = `assets/sounds/${id}.wav`
    return bundle
  }, {})
}

export const ASSET_BUNDLES: Record<string, AssetBundle> = {
  config: {
    buildingsData: 'assets/data/gameplay/buildings.json',
    unitsData: 'assets/data/gameplay/units.json',
    resourcesData: 'assets/data/gameplay/resources.json',
    animalsData: 'assets/data/gameplay/animals.json',
    projectilesData: 'assets/data/gameplay/projectiles.json',
    cellsData: 'assets/data/gameplay/cells.json',
    greek: 'assets/data/civilizations/greek.json',
    roman: 'assets/data/civilizations/roman.json',
    egyptian: 'assets/data/civilizations/egyptian.json',
    asian: 'assets/data/civilizations/asian.json',
    babylonian: 'assets/data/civilizations/babylonian.json',
    celtic: 'assets/data/civilizations/celtic.json',
    nubian: 'assets/data/civilizations/nubian.json',
    technology: 'assets/data/technologies/technologies.json',
  },
  interface: {
    'pointers/move-target': 'assets/interface/pointers/move-target/texture.json',
  },
  terrain: {
    'terrain/desert': 'assets/terrain/desert/texture.json',
    'terrain/grass': 'assets/terrain/grass/texture.json',
    'terrain/water': 'assets/terrain/water/texture.json',
    'terrain/deep-water': 'assets/terrain/deep-water/texture.json',
  },
  border: {
    'water-borders/desert': 'assets/border/water-borders/desert/texture.json',
    'relief-borders/desert': 'assets/border/relief-borders/desert/texture.json',
    'relief-borders/water': 'assets/border/relief-borders/water/texture.json',
  },
  graphics: toTextureBundle('assets/graphics', [
    'environment/floor/desert-1',
    'environment/floor/desert-2',
    'environment/floor/desert-3',
    'buildings/egyptian/wall/level-3',
    'buildings/egyptian/wall/level-2',
    'buildings/greek/academy/age-2',
    'buildings/greek/barracks/multi-age',
    'buildings/greek/town-center/multi-age',
    'buildings/greek/siege-workshop/age-2',
    'buildings/greek/granary/multi-age',
    'buildings/greek/house/multi-age',
    'buildings/greek/government-center/multi-age',
    'buildings/greek/wall/level-3',
    'buildings/greek/market/multi-age',
    'buildings/greek/wall/level-2',
    'buildings/greek/storage-pit/multi-age',
    'buildings/greek/archery-range/multi-age',
    'buildings/greek/stable/multi-age',
    'buildings/greek/temple/multi-age',
    'buildings/greek/guard-tower/age-3',
    'buildings/greek/dock/age-2',
    'buildings/asian/wall/level-3',
    'buildings/asian/wall/level-2',
    'buildings/rubble/size-1',
    'buildings/rubble/size-2',
    'buildings/rubble/size-3',
    'buildings/babylonian/wall/level-3',
    'buildings/babylonian/wall/level-2',
    'buildings/shared/house',
    'buildings/shared/granary',
    'buildings/shared/archery-range',
    'animals/boar/action',
    'buildings/shared/wall/dithered',
    'buildings/rubble/farm-depleted',
    'resources/berrybush',
    'projectiles/bolt',
    'projectiles/arrow',
    'projectiles/fire-arrow',
    'buildings/shared/barracks',
    'buildings/shared/temple',
    'buildings/construction/size-1',
    'buildings/construction/size-2',
    'buildings/construction/size-3',
    'boats/wrecks/small',
    'boats/wrecks/medium',
    'boats/wrecks/large',
    'projectiles/fire-bolt',
    'environment/floor/desert-4',
    'environment/floor/desert-5',
    'environment/floor/desert-6',
    'environment/floor/desert-7',
    'buildings/shared/town-center',
    'environment/floor/grass-1',
    'environment/floor/grass-2',
    'environment/floor/grass-3',
    'environment/floor/grass-4',
    'environment/floor/grass-5',
    'environment/floor/grass-6',
    'environment/floor/grass-7',
    'environment/floor/grass-8',
    'environment/floor/grass-9',
    'environment/floor/grass-10',
    'environment/floor/desert-8',
    'environment/floor/desert-9',
    'environment/floor/desert-10',
    'environment/floor/desert-11',
    'environment/floor/desert-12',
    'units/ballista/dying',
    'animals/deer/dying',
    'animals/hare/dying',
    'animals/black-grouse/dying',
    'animals/boar/dying',
    'animals/fox/dying',
    'effects/fire/light',
    'buildings/shared/dock',
    'buildings/construction/dock',
    'buildings/rubble/dock',
    'projectiles/stone',
    'animals/deer/corpse',
    'animals/hare/corpse',
    'animals/black-grouse/corpse',
    'animals/boar/corpse',
    'animals/fox/corpse',
    'environment/birds/eagle',
    'units/ballista/standing',
    'buildings/shared/farm',
    'effects/fire/heavy',
    'effects/fire/medium',
    'resources/fish/salmon',
    'ui/rally-point-flag',
    'projectiles/fire-stone',
    'resources/tree/palm-1',
    'resources/tree/palm-2',
    'resources/tree/palm-3',
    'resources/tree/palm-4',
    'boats/fishing-boat',
    'boats/fishing-ship',
    'animals/deer/standing',
    'animals/deer/walking',
    'animals/deer/running',
    'animals/hare/standing',
    'animals/hare/walking',
    'animals/hare/running',
    'animals/boar/standing',
    'animals/boar/walking',
    'animals/boar/running',
    'animals/horse/standing',
    'animals/horse/walking',
    'animals/fox/standing',
    'animals/fox/walking',
    'animals/fox/running',
    'animals/black-grouse/standing',
    'animals/black-grouse/walking',
    'animals/black-grouse/flying',
    'resources/gold',
    'resources/tree/grass-1',
    'resources/tree/grass-2',
    'resources/tree/grass-3',
    'resources/tree/grass-4',
    'buildings/shared/market',
    'environment/birds/hawk',
    'buildings/shared/storage-pit',
    'resources/tree/dark-forest-1',
    'resources/tree/dark-forest-2',
    'resources/tree/dark-forest-3',
    'resources/tree/dark-forest-4',
    'environment/ground/stone-set-1',
    'environment/ground/stone-set-2',
    'environment/ground/stone-set-3',
    'environment/ground/stone-set-4',
    'environment/water/shore-set-1',
    'environment/water/shore-set-2',
    'environment/water/deep-set-1',
    'environment/water/deep-set-2',
    'environment/water/shore-set-3',
    'environment/water/shore-set-4',
    'environment/water/shore-set-5',
    'environment/water/shore-set-6',
    'environment/water/shore-set-7',
    'environment/water/shore-set-8',
    'environment/water/shore-set-9',
    'environment/water/shore-set-10',
    'resources/fish/small',
    'buildings/shared/wall/construction-flag',
    'buildings/shared/wall/level-1',
    'units/trooper/default/walking',
    'units/trooper/default/action',
    'units/trooper/default/corpse',
    'units/trooper/default/dying',
    'units/trooper/default/standing',
    'projectiles/spear',
    'buildings/shared/stable',
    'resources/stone',
    'resources/tree/fallen',
    'resources/tree/stump',
    'buildings/shared/watch-tower',
    'buildings/egyptian/dock/age-2',
    'buildings/egyptian/academy/age-2',
    'buildings/egyptian/barracks/multi-age',
    'buildings/egyptian/town-center/multi-age',
    'buildings/egyptian/siege-workshop/age-2',
    'buildings/egyptian/granary/multi-age',
    'buildings/egyptian/house/multi-age',
    'buildings/egyptian/government-center/multi-age',
    'buildings/egyptian/market/multi-age',
    'buildings/egyptian/storage-pit/multi-age',
    'buildings/egyptian/archery-range/multi-age',
    'buildings/egyptian/stable/multi-age',
    'buildings/egyptian/temple/multi-age',
    'buildings/egyptian/guard-tower/age-3',
    'buildings/asian/dock/age-2',
    'buildings/asian/academy/age-2',
    'buildings/asian/barracks/multi-age',
    'buildings/asian/town-center/multi-age',
    'buildings/asian/siege-workshop/age-2',
    'buildings/asian/granary/multi-age',
    'buildings/asian/house/multi-age',
    'buildings/asian/government-center/multi-age',
    'buildings/asian/market/multi-age',
    'buildings/asian/storage-pit/multi-age',
    'buildings/asian/archery-range/multi-age',
    'buildings/asian/stable/multi-age',
    'buildings/asian/temple/multi-age',
    'buildings/asian/guard-tower/age-3',
    'buildings/babylonian/dock/age-2',
    'buildings/babylonian/academy/age-2',
    'buildings/babylonian/barracks/multi-age',
    'buildings/babylonian/town-center/multi-age',
    'buildings/babylonian/siege-workshop/age-2',
    'buildings/babylonian/granary/multi-age',
    'buildings/babylonian/house/multi-age',
    'buildings/babylonian/government-center/multi-age',
    'buildings/babylonian/market/multi-age',
    'buildings/babylonian/storage-pit/multi-age',
    'buildings/babylonian/archery-range/multi-age',
    'buildings/babylonian/stable/multi-age',
    'buildings/babylonian/temple/multi-age',
    'buildings/babylonian/guard-tower/age-3',
    'units/ballista/action',
    'units/catapult/action',
    'units/catapult/dying',
    'units/stone-thrower/dying',
    'units/supercar/dying',
    'units/ballista/corpse',
    'units/catapult/corpse',
    'units/stone-thrower/corpse',
    'units/supercar/corpse',
    'units/catapult/standing',
    'units/stone-thrower/standing',
    'boats/shared/sail-5-direction',
    'boats/shared/sail-9-direction',
    'units/stone-thrower/action',
    'boats/light-transport',
    'boats/heavy-transport',
    'units/ballista/walking',
    'units/catapult/walking',
    'units/stone-thrower/walking',
    'resources/fish/whale',
    'boats/war-galley',
    'boats/scout-ship',
    'boats/trireme',
    'boats/juggernaut',
    'boats/fishing-boat/fishing-overlay',
    'boats/fishing-ship/fishing-overlay',
    'projectiles/bullet',
    'projectiles/impact/explosion',
    'units/supercar/walking',
    'projectiles/supercar-missile',
    'units/supercar/body',
  ]),
  sounds: toSoundBundle([
    'building-burning',
    'academy-completed-selected',
    'deer-lion-killed',
    'ahfrern',
    'isay',
    'olmars',
    'mining',
    'archery-range-completed-selected',
    'archer-attack',
    'archer-attack-2',
    'archer-attack-3',
    'archer-attack-4',
    'artifact-war-chest-moving',
    'attack-warning',
    'siege-weapon-destroyed',
    'ballista-weapon-completed-selected',
    'ballista-bolt-shot',
    'ballista-bolt-shot-2',
    'ballista-bolt-shot-3',
    'ballista-bolt-shot-4',
    'barracks-completed-selected',
    'dock-completed-selected',
    'target-hit',
    'ship-destroyed',
    'non-military-ship-completed',
    'constructing',
    'button-selected',
    'completed-unknown',
    'velaren',
    'catapult-stone-shot',
    'catapult-stone-shot-2',
    'catapult-stone-shot-3',
    'catapult-weapon-completed-selected',
    'catapult-weapon-destroyed',
    'siege-weapon-moving',
    'town-center-completed-selected',
    'farming',
    'wood-chopping',
    'ayohoyohoyo',
    'wololo',
    'ballista-bolt-shot-5',
    'donnahee',
    'darwin',
    'human-unit-killed',
    'human-unit-killed-2',
    'human-unit-killed-3',
    'human-unit-killed-4',
    'human-unit-killed-5',
    'human-unit-killed-6',
    'human-unit-killed-7',
    'human-unit-killed-8',
    'human-unit-killed-9',
    'human-unit-killed-10',
    'horse-unit-killed',
    'target-hit-2',
    'elephant-selected',
    'elephant-selected-2',
    'siege-workshop-selected',
    'eventide',
    'arectus',
    'building-destroyed',
    'building-destroyed-2',
    'building-destroyed-3',
    'farming-2',
    'building-burning-2',
    'building-burning-3',
    'small-splash',
    'attack-swipe',
    'berry-gathering',
    'horse-moving',
    'unknown-sound',
    'granary-completed-selected',
    'sword-clash',
    'human-unit-killed-11',
    'human-unit-killed-12',
    'human-unit-killed-13',
    'attack-grunt',
    'attack-grunt-2',
    'building',
    'horse-unit-die',
    'hayoyo',
    'steel-attack',
    'horse-unit-attack',
    'ship-sunk',
    'steel-attack-2',
    'homis',
    'horse',
    'horse-2',
    'horse-3',
    'horse-4',
    'arrow-shot',
    'house-completed-selected',
    'conan',
    'government-center-completed-selected',
    'attack-class-2',
    'attack-class-2-2',
    'attack-class-2-3',
    'market-completed-selected',
    'hytay',
    'human-unit-completed',
    'wonder-completed-selected',
    'ogloma',
    'mining-2',
    'abadacus',
    'werebus',
    'priest-completed',
    'villager-completed',
    'readimar',
    'next-age-reached',
    'brogan',
    'rudkit',
    'farm-completed-selected',
    'ship-sunk-2',
    'farming-3',
    'somus',
    'ship-sunk-3',
    'fish',
    'fish-2',
    'fish-3',
    'storage-pit-completed-selected',
    'sword-attack',
    'swing-sword-attack',
    'tinkle-sword-attack',
    'sword-attack-2',
    'temple-completed-selected',
    'tower-completed-selected',
    'unknown-sound-2',
    'yuluk',
    'yuri',
    'wall-fortification-completed-selected',
    'military-ship-completed-selected',
    'whale',
    'whale-2',
    'unknown-attack',
    'elephant-unit-moving',
    'sumaga',
    'water',
    'hmmm',
    'elephant-alligator-killed',
    'winsetts-z',
  ]),
}

export const ASSET_LOAD_SEQUENCE = [
  { bundle: 'config', messageKey: 'loadingConfig' },
  { bundle: 'interface', messageKey: 'loadingInterface' },
  { bundle: 'terrain', messageKey: 'loadingTerrain' },
  { bundle: 'border', messageKey: 'loadingBorder' },
  { bundle: 'graphics', messageKey: 'loadingGraphics' },
  { bundle: 'sounds', messageKey: 'loadingSounds' },
]
