type AssetBundle = Record<string, string>

function toTextureBundle(basePath: string, ids: string[]): AssetBundle {
  return ids.reduce((bundle: AssetBundle, id) => {
    bundle[id] = `${basePath}/${id}/texture.json`
    return bundle
  }, {})
}

function toBuildingShadowBundle(ids: string[]): AssetBundle {
  return ids.reduce((bundle: AssetBundle, id) => {
    bundle[`${id}/shadow`] = `assets/graphics/${id}/texture_shadow.png`
    return bundle
  }, {})
}

function toSoundBundle(ids: string[]): AssetBundle {
  return ids.reduce((bundle: AssetBundle, id) => {
    bundle[id] = `assets/sounds/${id}.wav`
    return bundle
  }, {})
}

function toOggSoundBundle(ids: string[]): AssetBundle {
  return ids.reduce((bundle: AssetBundle, id) => {
    bundle[id] = `assets/sounds/${id}.ogg`
    return bundle
  }, {})
}

export const ASSET_BUNDLES: Record<string, AssetBundle> = {
  config: {
    buildingsData: 'assets/data/gameplay/buildings.json',
    unitsData: 'assets/data/gameplay/units.json',
    resourcesData: 'assets/data/gameplay/resources.json',
    animalsData: 'assets/data/gameplay/animals.json',
    projectilesData: 'assets/data/gameplay/projectiles.json',
    equipmentData: 'assets/data/gameplay/equipment.json',
    cellsData: 'assets/data/gameplay/cells.json',
    greek: 'assets/data/civilizations/greek.json',
    roman: 'assets/data/civilizations/roman.json',
    egyptian: 'assets/data/civilizations/egyptian.json',
    asian: 'assets/data/civilizations/asian.json',
    babylonian: 'assets/data/civilizations/babylonian.json',
    celtic: 'assets/data/civilizations/celtic.json',
    nordic: 'assets/data/civilizations/nordic.json',
    nubian: 'assets/data/civilizations/nubian.json',
    technology: 'assets/data/technologies/technologies.json',
  },
  interface: {
    'pointers/move-target': 'assets/interface/pointers/move-target/texture.json',
  },
  terrain: {
    'terrain/desert': 'assets/terrain/desert/texture.json',
    'terrain/grass': 'assets/terrain/grass/texture.json',
    'terrain/dark-grass': 'assets/terrain/dark-grass/texture.json',
    'terrain/jungle': 'assets/terrain/jungle/texture.json',
    'terrain/dirt': 'assets/terrain/dirt/texture.json',
    'terrain/snow': 'assets/terrain/snow/texture.json',
  },
  border: {
    'desert-sand-water-border': 'assets/border/desert-sand-water-border/texture.json',
    'desert-relief': 'assets/border/desert-relief/texture.json',
    'dirt-relief': 'assets/border/dirt-relief/texture.json',
    'snow-relief': 'assets/border/snow-relief/texture.json',
    'water-surface-filter': 'assets/border/water-surface-filter/texture.json',
  },
  graphics: {
    ...toTextureBundle('assets/graphics', [
      'buildings/rubble/size-1',
      'buildings/rubble/size-2',
      'buildings/rubble/size-3',
      'buildings/age-0/house',
      'buildings/age-1/house',
      'buildings/age-0/granary',
      'buildings/age-1/granary',
      'buildings/age-0/archery-range',
      'buildings/age-1/archery-range',
      'animals/boar/action',
      'buildings/age-0/wall/dithered',
      'resources/berrybush',
      'projectiles/bolt',
      'projectiles/arrow_ceramic',
      'projectiles/arrow_copper',
      'projectiles/arrow_bronze',
      'projectiles/arrow_iron',
      'projectiles/fire-arrow',
      'buildings/age-0/barracks',
      'buildings/age-1/barracks',
      'buildings/age-0/temple',
      'buildings/age-1/temple',
      'buildings/construction/size-2',
      'buildings/construction/size-3',
      'buildings/construction/size-5',
      'projectiles/fire-bolt',
      'buildings/age-0/town-center',
      'buildings/age-1/town-center',
      'units/ballista/dying',
      'units/rider-legs',
      'animals/deer/dying',
      'animals/hare/dying',
      'animals/black-grouse/dying',
      'animals/boar/dying',
      'animals/fox/dying',
      'animals/horse/dying',
      'effects/fire/light',
      'projectiles/stone',
      'environment/birds/eagle',
      'units/ballista/standing',
      'effects/fire/heavy',
      'effects/fire/medium',
      'ui/rally-point-flag',
      'projectiles/fire-stone',
      'resources/wheat',
      'resources/tree/palm-1',
      'resources/tree/palm-2',
      'resources/tree/palm-3',
      'resources/tree/palm-4',
      'animals/deer/standing',
      'animals/deer/walking',
      'animals/deer/running',
      'animals/hare/standing',
      'animals/hare/walking',
      'animals/hare/running',
      'animals/boar/standing',
      'animals/boar/walking',
      'animals/boar/running',
      'animals/horse/standing',
      'animals/horse/walking',
      'animals/fox/standing',
      'animals/fox/walking',
      'animals/fox/running',
      'animals/black-grouse/standing',
      'animals/black-grouse/walking',
      'animals/black-grouse/flying',
      'resources/gold',
      'resources/copper',
      'resources/iron',
      'resources/tree/grass-1',
      'resources/tree/grass-2',
      'resources/tree/grass-3',
      'resources/tree/grass-4',
      'buildings/age-0/market',
      'buildings/age-1/market',
      'environment/birds/hawk',
      'buildings/age-0/storage-pit',
      'buildings/age-1/storage-pit',
      'resources/tree/dark-forest-1',
      'resources/tree/dark-forest-2',
      'resources/tree/dark-forest-3',
      'resources/tree/dark-forest-4',
      'buildings/age-0/wall/construction-flag',
      'buildings/age-0/wall/level-1',
      'projectiles/spear',
      'buildings/age-0/stable',
      'buildings/age-1/stable',
      'resources/stone',
      'resources/tree/fallen',
      'resources/tree/stump',
      'buildings/age-0/watch-tower',
      'buildings/age-1/watch-tower',
      'units/ballista/action',
      'units/catapult/action',
      'units/catapult/dying',
      'units/stone-thrower/dying',
      'units/ballista/corpse',
      'units/catapult/corpse',
      'units/stone-thrower/corpse',
      'units/catapult/standing',
      'units/stone-thrower/standing',
      'units/stone-thrower/action',
      'units/ballista/walking',
      'units/catapult/walking',
      'units/stone-thrower/walking',
      'buildings/portal',
      'animals/wolf/standing',
      'animals/wolf/walking',
      'animals/wolf/action',
      'animals/wolf/dying',
    ]),
    ...toBuildingShadowBundle([
      'buildings/rubble/size-1',
      'buildings/rubble/size-2',
      'buildings/rubble/size-3',
      'buildings/age-0/house',
      'buildings/age-1/house',
      'buildings/age-0/granary',
      'buildings/age-1/granary',
      'buildings/age-0/archery-range',
      'buildings/age-1/archery-range',
      'buildings/age-0/wall/dithered',
      'buildings/age-0/barracks',
      'buildings/age-1/barracks',
      'buildings/age-0/temple',
      'buildings/age-1/temple',
      'buildings/age-0/town-center',
      'buildings/age-1/town-center',
      'buildings/age-0/market',
      'buildings/age-1/market',
      'buildings/age-0/storage-pit',
      'buildings/age-1/storage-pit',
      'buildings/age-0/wall/construction-flag',
      'buildings/age-0/wall/level-1',
      'buildings/age-0/stable',
      'buildings/age-1/stable',
      'buildings/age-0/watch-tower',
      'buildings/age-1/watch-tower',
      'resources/gold',
      'resources/stone',
      'resources/copper',
      'resources/iron',
    ]),
  },
  sounds: {
    ...toSoundBundle([
      'building-burning',
      'deer-lion-killed',
      'ahfrern',
      'isay',
      'olmars',
      'mining',
      'archery-range-completed-selected',
      'archer-attack',
      'archer-attack-2',
      'archer-attack-3',
      'archer-attack-4',
      'artifact-war-chest-moving',
      'attack-warning',
      'siege-weapon-destroyed',
      'ballista-weapon-completed-selected',
      'ballista-bolt-shot',
      'ballista-bolt-shot-2',
      'ballista-bolt-shot-3',
      'ballista-bolt-shot-4',
      'barracks-completed-selected',
      'target-hit',
      'constructing',
      'button-selected',
      'completed-unknown',
      'velaren',
      'catapult-stone-shot',
      'catapult-stone-shot-2',
      'catapult-stone-shot-3',
      'catapult-weapon-completed-selected',
      'catapult-weapon-destroyed',
      'siege-weapon-moving',
      'town-center-completed-selected',
      'farming',
      'wood-chopping',
      'ayohoyohoyo',
      'wololo',
      'ballista-bolt-shot-5',
      'donnahee',
      'darwin',
      'human-unit-killed',
      'human-unit-killed-2',
      'human-unit-killed-3',
      'human-unit-killed-4',
      'human-unit-killed-5',
      'human-unit-killed-6',
      'human-unit-killed-7',
      'human-unit-killed-8',
      'human-unit-killed-9',
      'human-unit-killed-10',
      'horse-unit-killed',
      'target-hit-2',
      'elephant-selected',
      'elephant-selected-2',
      'siege-workshop-selected',
      'eventide',
      'arectus',
      'building-destroyed',
      'building-destroyed-2',
      'building-destroyed-3',
      'farming-2',
      'building-burning-2',
      'building-burning-3',
      'small-splash',
      'attack-swipe',
      'berry-gathering',
      'horse-moving',
      'unknown-sound',
      'granary-completed-selected',
      'sword-clash',
      'human-unit-killed-11',
      'human-unit-killed-12',
      'human-unit-killed-13',
      'attack-grunt',
      'attack-grunt-2',
      'building',
      'horse-unit-die',
      'hayoyo',
      'steel-attack',
      'horse-unit-attack',
      'steel-attack-2',
      'homis',
      'horse',
      'horse-2',
      'horse-3',
      'horse-4',
      'arrow-shot',
      'house-completed-selected',
      'conan',
      'attack-class-2',
      'attack-class-2-2',
      'attack-class-2-3',
      'market-completed-selected',
      'hytay',
      'human-unit-completed',
      'wonder-completed-selected',
      'ogloma',
      'mining-2',
      'abadacus',
      'werebus',
      'priest-completed',
      'villager-completed',
      'readimar',
      'next-age-reached',
      'brogan',
      'rudkit',
      'farm-completed-selected',
      'farming-3',
      'somus',
      'storage-pit-completed-selected',
      'sword-attack',
      'swing-sword-attack',
      'tinkle-sword-attack',
      'sword-attack-2',
      'temple-completed-selected',
      'tower-completed-selected',
      'unknown-sound-2',
      'yuluk',
      'yuri',
      'wall-fortification-completed-selected',
      'unknown-attack',
      'elephant-unit-moving',
      'sumaga',
      'water',
      'hmmm',
      'elephant-alligator-killed',
    ]),
    ...toOggSoundBundle([
      'heartbeat',
      'weather/light-rain',
      'weather/heavy-rain',
      'weather/light-wind',
      'weather/heavy-wind',
      'weather/thunder-1',
      'weather/thunder-2',
      'weather/thunder-3',
      'surface/bush-rustling-1',
      'surface/bush-rustling-2',
      'surface/bush-rustling-3',
    ]),
  },
}

export const ASSET_LOAD_SEQUENCE = [
  { bundle: 'config', messageKey: 'loadingConfig' },
  { bundle: 'interface', messageKey: 'loadingInterface' },
  { bundle: 'terrain', messageKey: 'loadingTerrain' },
  { bundle: 'border', messageKey: 'loadingBorder' },
  { bundle: 'graphics', messageKey: 'loadingGraphics' },
  { bundle: 'sounds', messageKey: 'loadingSounds' },
]
