type AssetBundle = Record<string, string>

function toTextureBundle(basePath: string, ids: string[]): AssetBundle {
  return ids.reduce((bundle: AssetBundle, id) => {
    bundle[id] = `${basePath}/${id}/texture.json`
    return bundle
  }, {})
}

function toBuildingShadowBundle(ids: string[]): AssetBundle {
  return ids.reduce((bundle: AssetBundle, id) => {
    bundle[`${id}/shadow`] = `assets/graphics/${id}/texture_shadow.png`
    return bundle
  }, {})
}

function toSoundBundle(ids: string[]): AssetBundle {
  return ids.reduce((bundle: AssetBundle, id) => {
    bundle[id] = `assets/sounds/${id}.wav`
    return bundle
  }, {})
}

function toOggSoundBundle(ids: string[]): AssetBundle {
  return ids.reduce((bundle: AssetBundle, id) => {
    bundle[id] = `assets/sounds/${id}.ogg`
    return bundle
  }, {})
}

export const ASSET_BUNDLES: Record<string, AssetBundle> = {
  config: {
    buildingsData: 'assets/data/gameplay/buildings.json',
    unitsData: 'assets/data/gameplay/units.json',
    resourcesData: 'assets/data/gameplay/resources.json',
    animalsData: 'assets/data/gameplay/animals.json',
    projectilesData: 'assets/data/gameplay/projectiles.json',
    equipmentData: 'assets/data/gameplay/equipment.json',
    cellsData: 'assets/data/gameplay/cells.json',
    greek: 'assets/data/civilizations/greek.json',
    roman: 'assets/data/civilizations/roman.json',
    egyptian: 'assets/data/civilizations/egyptian.json',
    asian: 'assets/data/civilizations/asian.json',
    babylonian: 'assets/data/civilizations/babylonian.json',
    celtic: 'assets/data/civilizations/celtic.json',
    nordic: 'assets/data/civilizations/nordic.json',
    nubian: 'assets/data/civilizations/nubian.json',
    technology: 'assets/data/technologies/technologies.json',
  },
  interface: {
    'pointers/move-target': 'assets/interface/pointers/move-target/texture.json',
  },
  terrain: {
    'terrain/desert': 'assets/terrain/desert/texture.json',
    'terrain/grass': 'assets/terrain/grass/texture.json',
    'terrain/dark-grass': 'assets/terrain/dark-grass/texture.json',
    'terrain/jungle': 'assets/terrain/jungle/texture.json',
    'terrain/dirt': 'assets/terrain/dirt/texture.json',
    'terrain/snow': 'assets/terrain/snow/texture.json',
  },
  border: {
    'desert-sand-water-border': 'assets/border/desert-sand-water-border/texture.json',
    'desert-relief': 'assets/border/desert-relief/texture.json',
    'dirt-relief': 'assets/border/dirt-relief/texture.json',
    'snow-relief': 'assets/border/snow-relief/texture.json',
    'water-surface-filter': 'assets/border/water-surface-filter/texture.json',
  },
  graphics: {
    ...toTextureBundle('assets/graphics', [
      'buildings/age-0',
      'buildings/age-1',
      'animals/boar/action',
      'buildings/wall/dithered',
      'resources/berrybush',
      'projectiles',
      'buildings/construction/size-2',
      'buildings/construction/size-3',
      'buildings/construction/size-5',
      'units/rider-legs',
      'animals/deer/dying',
      'animals/hare/dying',
      'animals/black-grouse/dying',
      'animals/boar/dying',
      'animals/fox/dying',
      'animals/horse/dying',
      'effects/fire/light',
      'effects/fire/heavy',
      'effects/fire/medium',
      'ui/rally-point-flag',
      'resources/wheat',
      'resources/tree/palm',
      'animals/deer/standing',
      'animals/deer/walking',
      'animals/deer/running',
      'animals/hare/standing',
      'animals/hare/walking',
      'animals/hare/running',
      'animals/boar/standing',
      'animals/boar/walking',
      'animals/boar/running',
      'animals/horse/standing',
      'animals/horse/walking',
      'animals/fox/standing',
      'animals/fox/walking',
      'animals/fox/running',
      'animals/black-grouse/standing',
      'animals/black-grouse/walking',
      'animals/black-grouse/flying',
      'resources/minerals',
      'resources/tree/grass',
      'resources/tree/dark-forest',
      'buildings/wall/construction-flag',
      'buildings/wall/level-1',
      'resources/tree/dead',
      'buildings/portal',
      'buildings/deco',
      'animals/wolf/standing',
      'animals/wolf/walking',
      'animals/wolf/action',
      'animals/wolf/dying',
    ]),
    ...toBuildingShadowBundle([
      'buildings/age-0',
      'buildings/age-1',
      'buildings/wall/dithered',
      'buildings/wall/construction-flag',
      'buildings/wall/level-1',
      'resources/minerals',
    ]),
    'buildings/age-0/shadow': 'assets/graphics/buildings/age-0/texture_shadow.json',
    'buildings/age-1/shadow': 'assets/graphics/buildings/age-1/texture_shadow.json',
    'resources/minerals/shadow': 'assets/graphics/resources/minerals/texture_shadow.json',
  },
  sounds: {
    ...toSoundBundle([
      'building-burning',
      'deer-lion-killed',
      'mining',
      'archery-range-completed-selected',
      'archer-attack',
      'archer-attack-2',
      'archer-attack-3',
      'archer-attack-4',
      'artifact-war-chest-moving',
      'attack-warning',
      'barracks-completed-selected',
      'target-hit',
      'constructing',
      'button-selected',
      'completed-unknown',
      'town-center-completed-selected',
      'farming',
      'wood-chopping',
      'human-unit-killed',
      'human-unit-killed-2',
      'human-unit-killed-3',
      'human-unit-killed-4',
      'human-unit-killed-5',
      'human-unit-killed-6',
      'human-unit-killed-7',
      'human-unit-killed-8',
      'human-unit-killed-9',
      'human-unit-killed-10',
      'horse-unit-killed',
      'target-hit-2',
      'elephant-selected',
      'elephant-selected-2',
      'building-destroyed',
      'building-destroyed-2',
      'building-destroyed-3',
      'farming-2',
      'building-burning-2',
      'building-burning-3',
      'small-splash',
      'attack-swipe',
      'berry-gathering',
      'horse-moving',
      'unknown-sound',
      'granary-completed-selected',
      'sword-clash',
      'human-unit-killed-11',
      'human-unit-killed-12',
      'human-unit-killed-13',
      'attack-grunt',
      'attack-grunt-2',
      'building',
      'horse-unit-die',
      'steel-attack',
      'horse-unit-attack',
      'steel-attack-2',
      'horse',
      'horse-2',
      'horse-3',
      'horse-4',
      'arrow-shot',
      'house-completed-selected',
      'attack-class-2',
      'attack-class-2-2',
      'attack-class-2-3',
      'market-completed-selected',
      'wonder-completed-selected',
      'mining-2',
      'next-age-reached',
      'farm-completed-selected',
      'farming-3',
      'storage-pit-completed-selected',
      'sword-attack',
      'swing-sword-attack',
      'tinkle-sword-attack',
      'sword-attack-2',
      'temple-completed-selected',
      'tower-completed-selected',
      'unknown-sound-2',
      'wall-fortification-completed-selected',
      'unknown-attack',
      'elephant-unit-moving',
      'water',
      'hmmm',
      'elephant-alligator-killed',
    ]),
    ...toOggSoundBundle([
      'heartbeat',
      'weather/light-rain',
      'weather/heavy-rain',
      'weather/light-wind',
      'weather/heavy-wind',
      'weather/night-ambience',
      'weather/ocean-ambience',
      'building/campfire-crackle',
      'weather/thunder-1',
      'weather/thunder-2',
      'weather/thunder-3',
      'surface/hero-footstep-grass-1',
      'surface/hero-footstep-grass-2',
      'surface/hero-footstep-grass-3',
      'surface/hero-footstep-dirt-1',
      'surface/hero-footstep-dirt-2',
      'surface/hero-footstep-dirt-3',
      'surface/hero-footstep-stone-1',
      'surface/hero-footstep-stone-2',
      'surface/hero-footstep-stone-3',
      'surface/bush-rustling-1',
      'surface/bush-rustling-2',
      'surface/bush-rustling-3',
    ]),
  },
}

export const ASSET_LOAD_SEQUENCE = [
  { bundle: 'config', messageKey: 'loadingConfig' },
  { bundle: 'interface', messageKey: 'loadingInterface' },
  { bundle: 'terrain', messageKey: 'loadingTerrain' },
  { bundle: 'border', messageKey: 'loadingBorder' },
  { bundle: 'graphics', messageKey: 'loadingGraphics' },
  { bundle: 'sounds', messageKey: 'loadingSounds' },
]
