/** Place-name pools inspired by each civilization; independent of the interface language. */
export const CIVILIZATION_SETTLEMENT_NAMES: Record<string, readonly string[]> = {
  Hellas: [
    'Athènes',
    'Sparte',
    'Corinthe',
    'Argos',
    'Thèbes',
    'Delphes',
    'Olympie',
    'Milet',
    'Éphèse',
    'Phocée',
    'Rhodes',
    'Mycènes',
  ],
  Latium: [
    'Roma',
    'Alba Longa',
    'Ostia',
    'Tibur',
    'Tusculum',
    'Praeneste',
    'Aricia',
    'Lavinium',
    'Antium',
    'Lanuvium',
    'Velitrae',
    'Laurentum',
  ],
  Kemet: [
    'Memphis',
    'Waset',
    'Iounou',
    'Abydos',
    'Saïs',
    'Bubastis',
    'Dendérah',
    'Edfou',
    'Nekhen',
    'Esna',
    'Tanis',
    'Akhmim',
  ],
  Sumeria: ['Uruk', 'Ur', 'Eridu', 'Lagash', 'Nippur', 'Kish', 'Umma', 'Shuruppak', 'Larsa', 'Isin', 'Adab', 'Girsu'],
  Xia: [
    'Yangcheng',
    'Anyang',
    'Luoyang',
    'Erlitou',
    'Zhengzhou',
    'Kaifeng',
    'Puyang',
    'Xinzheng',
    'Dengfeng',
    'Yanshi',
    'Gongyi',
    'Yuzhou',
  ],
  Alba: [
    'Tara',
    'Emain Macha',
    'Dun Ailinne',
    'Cruachan',
    'Uisneach',
    'Cashel',
    'Dunadd',
    'Dun Edin',
    'Alesia',
    'Bibracte',
    'Gergovie',
    'Camulodunum',
  ],
  Nord: [
    'Uppsala',
    'Birka',
    'Sigtuna',
    'Ribe',
    'Hedeby',
    'Roskilde',
    'Jelling',
    'Kaupang',
    'Nidaros',
    'Avaldsnes',
    'Lund',
    'Skara',
  ],
  Nobatia: [
    'Pachoras',
    'Qasr Ibrim',
    'Qustul',
    'Ballana',
    'Dendur',
    'Kalabsha',
    'Napata',
    'Dakke',
    'Sedeinga',
    'Sai',
    'Soleb',
    'Amara',
  ],
}
