export const HERO_ACTION_MOVE_SPEED_FACTOR = 0
export const HERO_LOCKED_STRAFE_MOVE_SPEED_FACTOR = 0.8
export const HERO_STEALTH_SPEED_FACTOR = 0.55
export const HERO_STEALTH_ANIMAL_DETECTION_FACTOR = 0.55
